config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  root 'projects#index'

  get 'login' => "sessions#new"
  resource :session
 
  get 'signup' => 'users#new'  
  resources :users

  resources :projects do
    resources :pledges
    resources :favorites
  end

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
 
  validates :amount, numericality: { greater_than: 0 }

  belongs_to :project
  belongs_to :user

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  before_action :require_signin
  before_action :require_admin, only: [:destroy]
  
  before_action :set_project

  def new
    @pledge = @project.pledges.new
  end

  def create
  	@pledge = @project.pledges.new(pledge_params)
    @pledge.user = current_user
  	
  	if @pledge.save
  	  redirect_to @project, notice: 'Thank you for your pledge!'
  	else
  	  render :new
  	end
  end

  def destroy
    @pledge = @project.pledges.find(params[:id])
    @pledge.destroy
    redirect_to @project, notice: 'Pledge is deleted!'
  end


private

  def set_project
  	@project = Project.find_by!(slug: params[:project_id])
  end

  def pledge_params
  	params.require(:pledge).permit(:amount)
  end
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/views/pledges/_index.html.erb
<ul class="media-list">
<% @pledges.each do |pledge| %>
  <li class="media">
     <%= link_to profile_image_for(pledge.user), pledge.user, class: 'pull-left' %>
    
    <div class="media-body">
      <h5 class="media-heading"><%= link_to pledge.user.name, pledge.user %></h5>
      <span class="time"><%= time_ago_in_words(pledge.created_at) %> ago</span>
    </div>

    <% if current_user_admin? %>
    <%= link_to 'Delete', project_pledge_path(@project, pledge), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </li>  
<% end  %>
</ul>

app/views/pledges/new.html.erb
<div class="container">
	
<div class="header">
    <h1><%= @project.name %></h1>
    <h4>by <%= @project.user.name %></h4>
</div>

<div class="container-border">
	<div class="col-md-8">
	  		<%= form_for([@project, @pledge]) do |f| %>
	  		<%= render 'shared/errors', object: @pledge %>
	  		<div class="form-group">
			    <%= f.label :amount, 'Enter your pledge amount' %>
				<%= f.number_field :amount, class: 'form-control form-lg' %>
			</div>	
			
			<%= f.submit 'Make a Pledge!', class: 'btn btn-lg btn-success' %>
			<% end %>
	</div>

	<div class="col-md-4">
		<div class="green-box">
		<strong>IMPORTANT</strong>
<p>Kickstarter does not guarantee projects or investigate a creator's ability to complete their project. It is the responsibility of the project creator to complete their project as promised, and the claims of this project are theirs alone.</p>
<a href="#">Learn more about accountability</a>
	 	</div>
	</div>
</div>
</div>