config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  root 'projects#index'

  get 'login' => "sessions#new"
  resource :session
 
  get 'signup' => 'users#new'  
  resources :users

  resources :projects do
    resources :pledges
    resources :favorites
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :pledges, dependent: :destroy
  has_many :backers, through: :pledges, source: :user

  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags 

  belongs_to :user

  has_attached_file :image

  before_validation :generate_slug
  
  validates :name, presence: true, uniqueness: true
  validates :slug, uniqueness: true
  validates :pledging_ends_on, presence: true
  validates :description, length: { minimum: 5 }
  validates :target_pledge_amount, numericality: {
     greater_than: 0
  }
  validates_attachment :image, 
  :content_type => { :content_type => ['image/jpeg', 'image/png'] },
  :size => { :less_than => 1.megabyte }

  
  scope :pledging, -> { where('pledging_ends_on > ?', Time.now) }

  scope :recent, ->(max=4) { pledging.order(created_at: :desc).limit(max) }
  
  scope :endsoon, ->(max=4) { pledging.order(pledging_ends_on: :asc).limit(max)  }

  def expired?
  	pledging_ends_on < Time.now
  end

 

  def pledge_amount_sum
    pledges.sum(:amount)
  end

  def pledge_percentage
     (pledge_amount_sum / target_pledge_amount) * 100
  end

  def success?
    pledge_percentage >= 100
  end

  def generate_slug
    self.slug ||= name.parameterize if name
  end

  def to_param
    slug
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show]
  before_action :set_current_project, only: [:edit, :update, :destroy]
  before_action :require_signin, except: [:index, :show]
  

  def index
    @categories = Category.all
    @projects = Project.pledging
    @recent_projects = Project.recent
    @endsoon_projects = Project.endsoon
  end

  def show
    @pledges = @project.pledges.order(created_at: :desc)
    @backers = @project.backers
    @fans = @project.fans
    @categories = @project.categories

    if current_user
      @current_pledge = current_user.pledges.find_by(project_id: @project.id)
      @current_favorite = current_user.favorites.find_by(project_id: @project.id)
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    @project.user = current_user

    if @project.save
      redirect_to @project, notice: 'Your project is successfully created!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
 	if @project.update(project_params)
  	  redirect_to @project, notice: 'Your project is successfully edited!'
    else
      render 'edit'
    end 	
  end

  def destroy
    @project.delete
    redirect_to root_path, notice: 'Your project is gone!'
  end

private
  def project_params
  	params.require(:project).permit(:name, :description, :target_pledge_amount, :pledging_ends_on, :image, category_ids: [])
  end

  def set_project
    @project = Project.find_by!(slug: params[:id])
  end

  def set_current_project
    @project = current_user.projects.find_by!(slug: params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def pledge_end_format(project)
  	if project.expired?
  		content_tag(:span, "Expired", class: "label label-danger")
  	else
  		distance_of_time_in_words(Time.now, project.pledging_ends_on)
  	end
  end

  def pledge_result(project)
  	if project.success?
  	  '100%'
  	else
  	  number_to_percentage(project.pledge_percentage, precision:1)
  	end
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'shared/errors', object: @project %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 7, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %> <br/>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </div>

  <div class="form-group short">
    <%= f.label :target_pledge_amount %>
    <%= f.number_field :target_pledge_amount, class: "form-control" %>
  </div>

  <div class="form-group short">
    <%= f.label :pledging_ends_on %>
    <%= f.date_field :pledging_ends_on, class: "form-control" %>
  </div>

  <div class="form-group short">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-lg btn-primary"  %>
<% end %>

app/views/projects/_profilelist.html.erb
  <ul class="media-list">
      <% object.each do |user| %>
       <li class="media">
             <%= link_to profile_image_for(user), user, class: 'pull-left' %>
                 <div class="media-body">
                <h5 class="media-heading"><%= link_to user.name, user %></h5>
                     <span class="time"><%= time_ago_in_words(user.created_at) %> ago</span>
                </div>
           
              </li>  
          <% end  %>
  </ul>

app/views/projects/edit.html.erb
<div class="container">
<h2> Editing <%= @project.name %></h2>

<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag('main1.png') %>
          
        </div>
        <div class="item">
         <%= image_tag('main2.png') %>
          
        </div>
        <div class="item">
          <%= image_tag('main3.png') %>
          
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>   


<div class="container">

<div class="row">
 <h3>New & Noteworthy</h3><br>
   <%= render 'shared/thumbnail_small', object: @recent_projects %>
</div>
<div class="row">
 <h3>End Soon</h3><br>
   <%= render 'shared/thumbnail_small', object: @endsoon_projects %>
</div>
</div>

app/views/projects/new.html.erb
<h2>Create new project</h2>

<%= render 'form' %>

app/views/projects/show.html.erb
<% content_for(:title, @project.name) %>

<div class="container">
<div class="header">
    <h1><%= @project.name %></h1>
    <h4>by <%= link_to @project.user.name, @project.user %></h4>
</div>


<div class="container-border">
  <div class="row">
<div class="col-md-8">
     <%= image_for(@project) %>
    <hr></hr>


  <div class="row">
    <% @categories.each do |category| %>
      <span class="label label-default"><%= link_to category.name, category %></span>
    <% end %>
  </div>


   <div class="row">
  	<%= @project.description %>
  </div>


<% if current_user?(@project.user)  %>
<ul class="pager">
  <li class="previous">
  	<%= link_to '<span class="glyphicon glyphicon-pencil"></span> Edit'.html_safe, edit_project_path %></li>
  	<li class="previous">
  	<%= link_to '<span class="glyphicon glyphicon-trash"></span> Delete'.html_safe, @project, method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>
<% end %>


 </div>

 <div class="col-md-4">
  <div class="row">
   <strong>
     <h1><%= @project.pledges.count %></h1>
       <%= 'backer'.pluralize(@project.pledges.count) %>
 </strong>
  </div>
    
   <div class="row">
   <strong>
     <h1><%= number_to_currency(@project.pledge_amount_sum, precision:0) %></h1>
     pledged of <%= number_to_currency(@project.target_pledge_amount, precision:0) %> goal
 </strong>
  </div>

  <div class="row"><strong>
    <h1>
  	<%= distance_of_time_in_words(Time.now, @project.pledging_ends_on) %> </h1>
  	to go
  </strong>
   </div>

<!-- Pledge Button -->
   <% if @current_pledge  %>
      <button class="btn btn-success btn-lg btn-block" disabled>You've already pledged!</button><br>
   <% else  %>
   <%= button_to "Back This Project", new_project_pledge_path(@project), method: :get, class: "btn btn-success btn-lg btn-block" %><br>
   <% end  %>

<!-- Favorite Button -->
    <% if @current_favorite %>
      <%= link_to '<span class="glyphicon glyphicon-heart"></span> Remove from Fav'.html_safe, project_favorite_path(@project, @current_favorite), method: :delete, class: "unfav" %>   
    <% else  %>
      <%= link_to '<span class="glyphicon glyphicon-heart"></span> Add to Fav'.html_safe, project_favorites_path(@project), method: :post, class: "fav" %> 
   <% end  %>
  
<!-- Fans -->
<% if @fans.any? %>
  <hr></hr>
    <div class="row">
      <h4>Fans (<%= @fans.count %>)</h4>
        <%= render 'profilelist', object: @fans  %>
    </div>
<% end %>

<!-- Backers -->
<% if @backers.any? %>
  <hr></hr>
    <div class="row">
      <h4>Backers (<%= @backers.count %>)</h4>
        <%= render 'profilelist', object: @backers  %>
    </div>
<% end %>

 </div>
</div>
</div>
</div>