config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  root 'projects#index'

  get 'login' => "sessions#new"
  resource :session
 
  get 'signup' => 'users#new'  
  resources :users

  resources :projects do
    resources :pledges
    resources :favorites
  end

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
 <% if key == "notice"  %>
	<div class="alert alert-success alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= value %>
    </div>
  <% else %>
	<div class="alert alert-danger alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= value %>
    </div>
  <% end  %>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><%= image_tag('kickstarter-logo-light.png', height: 16) %></a>          
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
             <li><%= link_to "Discover", categories_path %></li>
             <li><%= link_to "Start", new_project_path %></li>
             <% if current_user_admin?  %>
             <li><%= link_to "Admin", users_path %>
             <% end  %>
          </ul>

          <ul class="nav navbar-nav navbar-right"> 
          <% if current_user  %>   
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'My profile', current_user %></li>
                <li><%= link_to 'Account Setting', edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Log in", login_path %></a></li>    
          <% end  %>        
          </ul>

        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
 
<!-- /.carousel -->    


   <%= yield %>
	<%= render 'layouts/flashes' %>


</body>
</html>